### PR TITLE
Handled UTF-8 BOM

### LINKED ISSUE #1155: Missing support of byte order mark
Markdown files encoded in UTF8+BOM can be rendered incorrectly, as `#` in the first line is not handled.

### PR DESCRIPTION
**Pull request by FrankHB**
Fixed #1155 .

### CODE REVIEW

File: src/book/book.rs [hunk 1]
```diff
@@ -264,6 +264,10 @@ fn load_chapter<P: AsRef<Path>>(
             format!("Unable to read \"{}\" ({})", link.name, location.display())
         })?;
 
+        if content.as_bytes().starts_with(b"\xef\xbb\xbf") {
+            content = content[3..].to_string()
```
Comment (ehuss) [inline src/book/book.rs:268]: Just to avoid the extra allocation, perhaps this could be `content.replace_range(..3, "");`

**Comment by FrankHB** [comment]
Not sure where should be the test. Is an additional BOM in `tests/dummy_book/src/first/unicode.md` enough?

**Comment by ehuss** [comment]
I'm a little concerned about having invisible bytes in a file. `unicode.md` is already quite subtle. But I think if you have an editor that can't handle a BOM properly, it will have a risk of corrupting the existing unicode, so it's probably fine.

My only other idea is to create a simple 1-chapter book in a temp directory like `book_with_a_reserved_filename_does_not_build` does.  Whichever seems easiest!

**Comment by FrankHB** [comment]
Sorry, I don't get the point of the temp directory.

As of the subtleness... I largely agree. Nevertheless, I can use a hex editor to make sure only the BOM is inserted exactly. Anyway, the visible part of the file has already warn us about this. (Or one more visible warning about invisible bytes?)

**Comment by ehuss** [comment]
Creating a book in Rust code (and writing it to a temp directory) would allow writing the content in a Rust string where the characters can be escaped and explicit. For example, `fs::write(chapter, "\u{feff}# Example chapter")`.

**Review by ehuss — APPROVED** [review]
Thanks!
